// <auto-generated />
using System;
using Dal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(dbcontext))]
    partial class dbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Common.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Common.Models.Expenditure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("amountPaid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoryId");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("ExpenditureSum")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("expenditureSum");

                    b.Property<int>("InvoiceNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoiceNum");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isAccepted");

                    b.Property<string>("OrdererName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ordererName");

                    b.Property<int>("SchoolSymbol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schoolSymbol");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplierNum");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SchoolSymbol");

                    b.HasIndex("SupplierNum");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("Common.Models.School", b =>
                {
                    b.Property<int>("SchoolSymbol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schoolSymbol");

                    b.Property<decimal>("Budget")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("budget");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schoolName");

                    b.HasKey("SchoolSymbol");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Common.Models.Supplier", b =>
                {
                    b.Property<int>("LicensedNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bankCode");

                    b.Property<string>("NameOfOwnerAccount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nameOfOwnerAccount");

                    b.Property<int>("NumOfBankAccount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numOfBankAccount");

                    b.Property<int>("NumOfBankBranch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numOfBankBranch");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("supplierName");

                    b.HasKey("LicensedNum");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolSymbol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schoolSymbol");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("userName");

                    b.HasKey("Id");

                    b.HasIndex("SchoolSymbol");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Common.Models.Expenditure", b =>
                {
                    b.HasOne("Common.Models.Category", "Category")
                        .WithMany("Expenditures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.School", "SchoolSymbolNavigation")
                        .WithMany("Expenditures")
                        .HasForeignKey("SchoolSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Common.Models.Supplier", "SupplierNumNavigation")
                        .WithMany("Expenditures")
                        .HasForeignKey("SupplierNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SchoolSymbolNavigation");

                    b.Navigation("SupplierNumNavigation");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.HasOne("Common.Models.School", "SchoolSymbolNavigation")
                        .WithMany("Users")
                        .HasForeignKey("SchoolSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolSymbolNavigation");
                });

            modelBuilder.Entity("Common.Models.Category", b =>
                {
                    b.Navigation("Expenditures");
                });

            modelBuilder.Entity("Common.Models.School", b =>
                {
                    b.Navigation("Expenditures");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.Models.Supplier", b =>
                {
                    b.Navigation("Expenditures");
                });
#pragma warning restore 612, 618
        }
    }
}
